### ISSUE TITLE
[v1.0.0] File paths in `url()` broken (`css-loader`)

### ISSUE THREAD

**Issue by pastelsky** [webpack-contrib/file-loader#181]
I upgraded to `file-loader@1` and this is how `@font-face` definitions are being rendered - 
```css
@font-face {
  font-family: Mrs Eaves XL Serif;
  font-style: normal;
   /* Font file paths are broken */
  src: url([object object]) format("woff2"), 
    url([object object]) format("woff"), 
    url([object object]) format("truetype")
}
```
The font paths are rendered just fine if I downgrade to `v0.11.2`

My loader config looks like - 
```js
      {
        test: /\.(woff|woff2|ttf)/,
        loader: 'file-loader',
        query: {
          context: path.join(paths.source, 'assets/fonts'),
          name: path.join('..','fonts/[path][name].[hash:5].[ext]'),
        },
      },
```
This might be happening for outside `url()` too, but don't have any use cases to test in my current project.

### Versions
webpack v3.4.1
node v8.1.2
file-loader v1.0.0
