### ISSUE TITLE
Outputting [Object object] instead of URL for CSS file url functions

### ISSUE THREAD

**Issue by IronSean** [webpack-contrib/file-loader#353]
- Operating System: Windows 10
- Node Version: v12.13.1
- NPM Version: 6.12.1
- webpack Version: 4.41.4
- file-loader Version: 5.0.2

### Expected Behavior

generate CSS like this (as it did in file-loader 4.x):
```css
body {
    background: url(http://localhost:8080/dist/bce4508….png) #ffffff;
}
```

### Actual Behavior

generates CSS as 
```css
body {
  background: url([object Module]) #ffffff;
}
```

### Code

The use of `file-loader` is completely default currently, I'm working on a repro below as the whole webpack config is quite large.

### How Do We Reproduce?

I'm working on a repro I can provide.
