### ISSUE TITLE
file-loader has a bug to generate image path in css file when I use css file in node_models

### ISSUE THREAD

**Issue by martinko2009** [webpack-contrib/file-loader#92]
I use windows7, node: node-v4.4.5-x64, npm: 2.15.5, url-loader: 0.5.7,file-loader:0.9.0,webpack:1.13.1

In the js file,I write like below:

```
require("layer-dialog/src/skin/layer.css");
```

this css file is from node_modules directory, 
when I use npm to install the component in this directory

webpack.config.js configurtion like below:

```
module:{
        loaders: [
          {test: /\.vue$/, loader: 'vue' },
          {
                    test: /\.js$/,
                    exclude: /node_modules/,
                    loader: 'babel'
          },
          {test: /\.css$/, loader: "style!css" },
          {test: /\.scss$/, loader: "style!css!sass"},
          {test: /\.less$/, loader: "style!css!less"},
          {
        test: /\.(png|jpg|gif|svg)$/,
                    loader: 'url',
                    query: {
                            limit: 1500,
                            name: 'imgs/[name].[ext]?[hash:7]'
                    }
          }
        ]
    },
```

but after complie, I open the js file,the image path generated is like below:

```
"imgs/node_modules\\\\layer-dialog\\\\src\\\\skin\\\\default\\\\icon.png?551539f"
```

the path is wrong. The correct path will be like below:

```
 "imgs/node_modules/layer-dialog/src/skin/default/icon.png?551539f"
```

I found the problem is caused from config of  name: 'imgs/[name].[ext]?[hash:7]' in the webpack.config.js.
The value of [name] is node_modules\\layer-dialog\\src\\skin\\default\\icon,so after 
I compiled project, it will generate the path like this.

How can I resolve this problem?

**Comment by evilebottnawi** [comment]
@martinko2009 problem is actual? If yes can your provide minimal reproducible test repo?

**Comment by alihammad-gist** [comment]
The file-loader doesn't copy font files from `node_modules` to `dist/font` folder but it does copy it from my `source` folder to `dist/font`. Here you can see how path to fonts inside `node_modules` is generated. Anyone know why this difference, am I missing an option that would enable moving files from inside `node_modules`?
```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url(../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot);
  src: url(../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot?#iefix) format("embedded-opentype"), url(../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2) format("woff2"), url(../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff) format("woff"), url(../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf) format("truetype"), url(../node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular) format("svg"); }
```

Here is an example of generated path of font files that reside outside node_modules ie inside my src directory
```css 
@font-face {
  font-family: 'Ubuntu';
  src: url("fonts/ubuntu/Ubuntu Bold.eot");
  src: url("fonts/ubuntu/Ubuntu Bold.eot?#iefix") format("embedded-opentype"), url("fonts/ubuntu/Ubuntu Bold.woff2") format("woff2"), url("fonts/ubuntu/Ubuntu Bold.woff") format("woff"), url("fonts/ubuntu/Ubuntu Bold.svg#Ubuntu Bold") format("svg");
  font-weight: 700;
  font-style: normal;
  font-stretch: normal;
  unicode-range: U+0020-2074; }
```
This is my webpack configuration.
```js
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {

	entry: {
		all: './src/all.scss',
	},

	output: {
		path: __dirname + '/dist',
		filename: '[name].bundle.js'
	},

	module: {
		rules: [
			{
				test: /\.woff($|\?)|\.woff2($|\?)|\.ttf($|\?)|\.eot($|\?)|\.svg($|\?)/,
				loader: 'url-loader',
				query: {
					useRelativePath: true,
					outputPath: "fonts/",
					include: './node_modules/',
					limit: 10,
					name: '[name].[ext]'
				}
			},
			{
				test: /\.css$/,
				loader: ExtractTextPlugin.extract({
					loader: 'css-loader?importLoaders=1',
				})
			},
			{
				test: /\.(sass|scss)$/,
				loader: ExtractTextPlugin.extract([
					'css-loader',
					'sass-loader'
				])
			}
		]
	},

	plugins: [
		new ExtractTextPlugin({
			filename: '[name].bundle.css',
			allChunks: true,
		})
	],

	watchOptions: {
		poll: true
	}
}
```
